version: 2
updates:
  - package-ecosystem: "uv"
    directory: "/backend"
    schedule:
      interval: "weekly"

  - package-ecosystem: "uv"
    directory: "/services/auth"
    schedule:
      interval: "weekly"

  - package-ecosystem: "uv"
    directory: "/services/convertor"
    schedule:
      interval: "weekly"

  - package-ecosystem: "uv"
    directory: "/services/moderation"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
