version: 2
updates:
  - package-ecosystem: "uv"
    directories:
      - "/backend"
      - "/service/auth"
      - "/service/convertor"
      - "/service/moderation"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
