version: 2
updates:
  - package-ecosystem: "uv"
    directory: "/backend"
    schedule:
      interval: "weekly"

  - package-ecosystem: "uv"
    directory: "/service/auth"
    schedule:
      interval: "weekly"

  - package-ecosystem: "uv"
    directory: "/service/convertor"
    schedule:
      interval: "weekly"

  - package-ecosystem: "uv"
    directory: "/service/moderation"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
