workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH =~ /^dev/'
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always

variables:
  UV_VERSION: "0.9.18"
  PYTHON_VERSION: "3.12"
  BASE_LAYER: bookworm-slim
  UV_LINK_MODE: copy

default:
  tags:
    - local

stages:
  - lint
  - test
  - security
  - auto-pr
  - detect
  - deploy

include:
  - local: 'ci/python.yml'
  - local: 'ci/node.yml'
  - local: 'ci/deploy.yml'
  - local: 'ci/security.yml'
  - local: 'ci/auto-pr.yml'

#pages:
#  stage: deploy
#  image: node:22
#  script:
#    - npm install
#    - npm run build
#    - cp -r public/ public-pages/
#  artifacts:
#    paths:
#      - public-pages
#  only:
#    - main
