repos:
  # ----------------- General checks -----------------
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        exclude: '(^|/|\\)\.venv($|/)'

      - id: end-of-file-fixer
        exclude: '(^|/|\\)\.venv($|/)'

      - id: check-yaml
        exclude: '(^|/|\\)\.venv($|/)'

      - id: check-added-large-files
        exclude: '(^|/|\\)\.venv($|/)'

      - id: detect-private-key
        exclude: '(^|/|\\)\.venv($|/)'

  # ----------------- Python -----------------
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        language_version: python3.12
        files: \.py$
        exclude: '(^|/|\\)\.venv($|/)'

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.12.10
    hooks:
      - id: ruff
        language_version: python3.12
        files: \.py$
        exclude: '(^|/|\\)\.venv($|/)'
        args: [ "--fix" ]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.0
    hooks:
      - id: mypy
        language_version: python3.12
        files: \.py$
        exclude: '(^|/|\\)\.venv($|/)'

  # ----------------- Node / JS / TS -----------------
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.34.0
    hooks:
      - id: eslint
        entry: npx eslint --config frontend/eslint.config.js
        files: ^frontend/.*\.(js|ts|jsx|tsx)$
        exclude: "(^|/)[.]venv/|node_modules/"

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        files: ^frontend/.*\.(js|ts|css|scss|json|md|yaml|yml)$
        exclude: "(^|/)[.]venv/|node_modules/"

  # ----------------- Dependency checks -----------------
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
      - id: gitlint
        exclude: '(^|/|\\)\.venv($|/)'

  - repo: https://github.com/pycqa/bandit
    rev: 1.8.6
    hooks:
      - id: bandit
        language_version: python3.12
        args:
          [
            "-c",
            "bandit.yaml",
            "-r",
            ".",
            "-f",
            "custom",
            "--msg-template",
            "{relpath}:{line}:{col} {severity} {test_id} {msg}",
          ]
        pass_filenames: false
        additional_dependencies: [ "charset-normalizer" ]
