repos:
  - repo: local
    hooks:

      - id: black
        name: black
        entry: black .
        language: system
        types: [ python ]
        pass_filenames: true

      - id: isort
        name: isort
        entry: isort .
        language: system
        types: [ python ]
        pass_filenames: true

      - id: ruff
        name: ruff
        entry: ruff check . --fix
        language: system
        types: [ python ]
        pass_filenames: true

      - id: mypy
        name: mypy
        entry: mypy .
        language: system
        types: [ python ]
        pass_filenames: true
