apiVersion: v1
kind: Service
metadata:
  name: {{ include "video-streaming.fullname" . }}-backend
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ include "video-streaming.name" . }}
    component: backend
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
