services:
  bff:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: bff_service
    expose:
      - "8000"
    depends_on:
      - postgres
      - ffmpeg
      - minio
      - rabbitmq
    logging:
      driver: "json-file"
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: frontend_service
    expose:
      - "8001"
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    env_file:
      - ../backend/src/database.env
    expose:
      - "${POSTGRES_PORT}"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 1m30s
      timeout: 5s
      retries: 5
      start_period: 40s
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"

  ffmpeg:
    build:
      context: ../services/convertor
      dockerfile: Dockerfile
    container_name: ffmpeg_service
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    expose:
      - "8002"
    tty: true
    stdin_open: true
    depends_on:
      rabbitmq:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"

  minio:
    image: minio/minio:latest
    container_name: minio_service
    env_file:
      - ../backend/src/s3.env
    expose:
      - "9000"
      - "9001"
    restart: unless-stopped
    hostname: minio
    environment:
      MINIO_BROWSER_REDIRECT_URL: http://localhost/minio/ui
      MINIO_PROMETHEUS_URL: http://prometheus:9090
    command: minio server /minio_data --console-address ":9001"
    volumes:
      - minio_data:/minio_data
    healthcheck:
      test: [ "CMD", "mc", "ready", "local" ]
      interval: 5s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"

  nginx:
    image: nginx:alpine
    container_name: nginx_gateway
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ../gateway/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - bff
      - frontend
    logging:
      driver: "json-file"
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"

  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: rabbit_service
    restart: always
    expose:
      - "5672"
      - "15672"
    healthcheck:
      test: [ "CMD-SHELL", "rabbitmqctl status" ]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    expose:
      - "9080"
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers
      - /var/run/docker.sock:/var/run/docker.sock
      - ../monitoring/promtail-config.yaml:/etc/promtail/promtail-config.yaml
    command: -config.file=/etc/promtail/promtail-config.yaml
    privileged: true

  loki:
    image: grafana/loki:latest
    container_name: loki
    expose:
      - "3100"
    volumes:
      - ../monitoring/loki-config.yaml:/etc/loki/loki-config.yaml

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    expose:
      - "9090"
    volumes:
      - ../monitoring/prometheus.yaml:/etc/prometheus/prometheus.yaml
      - prometheusdata:/prometheus

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    expose:
      - "3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
      - GF_SERVER_ROOT_URL=http://localhost/grafana
    volumes:
      - ../monitoring/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - grafanadata:/var/lib/grafana


networks:
  default:
    name: video_streaming_network
    external: true

volumes:
  minio_data:
  grafanadata:
  prometheusdata:

# docker compose -p video_streaming_stack -f ./Docker/docker-compose.yml build
# docker compose -p video_streaming_stack -f ./Docker/docker-compose.yml up -d

#docker compose -p video_streaming_stack -f ./Docker/docker-compose.yml up -d --build