services:
  bff:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: bff_service
    expose:
      - "8000"
    depends_on:
      - postgres
      - ffmpeg
      - minio
      - rabbitmq
    volumes:
      - ../backend/alembic/versions:/app/alembic/versions
    environment:
      - VAULT_ADDR=${VAULT_ADDR}
      - VAULT_TOKEN=${VAULT_TOKEN}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://127.0.0.1:8000/api/health/live" ]
      interval: 10s
      timeout: 3s
      retries: 3
    logging:
      driver: "json-file"
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"

  frontend:
      build:
        context: ../frontend
        dockerfile: Dockerfile
      container_name: frontend_service
      expose:
        - "8001"
      depends_on:
        - postgres
      develop:
        watch:
          - action: rebuild
            path: ../frontend

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - "5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 1m30s
      timeout: 5s
      retries: 5
      start_period: 40s
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"

  ffmpeg:
    build:
      context: ../services/convertor
      dockerfile: Dockerfile
    container_name: ffmpeg_service
    environment:
      - VAULT_ADDR=${VAULT_ADDR}
      - VAULT_TOKEN=${VAULT_TOKEN}
      - NVIDIA_VISIBLE_DEVICES=all
    expose:
      - "8002"
    depends_on:
      rabbitmq:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"

  minio:
    image: minio/minio:latest
    container_name: minio_service
    expose:
      - "9000"
      - "9001"
    restart: unless-stopped
    hostname: minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_ENDPOINT_URL: ${MINIO_ENDPOINT_URL}
      MINIO_REGION_NAME: ${MINIO_REGION_NAME}

      MINIO_BROWSER_REDIRECT_URL: http://localhost/minio/ui
      MINIO_PROMETHEUS_URL: http://prometheus:9090
    #      MINIO_AUDIT_WEBHOOK_ENABLE_logger: "on"
    #      MINIO_AUDIT_WEBHOOK_ENDPOINT_logger: "http://loki:3100/loki/api/v1/push"
    #      MINIO_KMS_AUTO_ENCRYPTION: "on"
    #      MINIO_KMS_MASTER_KEY: "my-key:32byteslongsecretkeymustbe!"
    command: minio server /minio_data --console-address ":9001"
    volumes:
      - minio_data:/minio_data
    healthcheck:
      test: [ "CMD", "mc", "ready", "local" ]
      interval: 5s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"

  nginx:
    image: nginx:alpine
    container_name: nginx_gateway
    restart: always
    ports:
      - "80:80"
    volumes:
      - ../gateway/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      bff:
        condition: service_healthy
      vault:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"

  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: rabbit_broker
    restart: always
    expose:
      - "5672"
      - "15672"
    healthcheck:
      test: [ "CMD-SHELL", "rabbitmqctl status" ]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    expose:
      - "9080"
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers
      - /var/run/docker.sock:/var/run/docker.sock
      - ../monitoring/promtail-config.yaml:/etc/promtail/promtail-config.yaml
    command: -config.file=/etc/promtail/promtail-config.yaml
    privileged: true

  loki:
    image: grafana/loki:latest
    container_name: loki
    expose:
      - "3100"
    volumes:
      - ../monitoring/loki-config.yaml:/etc/loki/loki-config.yaml

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    expose:
      - "9090"
    volumes:
      - ../monitoring/prometheus.yaml:/etc/prometheus/prometheus.yaml
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yaml"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    expose:
      - "3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
      - GF_SERVER_ROOT_URL=http://localhost/grafana
    volumes:
      - ../monitoring/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - grafana_data:/var/lib/grafana

  keycloak:
    image: keycloak/keycloak:latest
    command: start-dev
    expose:
      - "8080"
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/KeycloakDB
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_PROXY: edge                          # if behind nginx/traefik proxy
      KC_HEALTH_ENABLED: "true"
      KC_METRICS_ENABLED: "true"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8080/health/ready || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"

  vault:
    image: hashicorp/vault:latest
    command: sh -c "chown -R vault:vault /opt/vault/data && vault server -config=/etc/vault/vault.hcl"
    container_name: vault
    restart: always
    expose:
      - "8200"
    cap_add:
      - IPC_LOCK
    environment:
      - VAULT_ADDR=http://vault:8200
      - VAULT_API_ADDR=http://vault:8200
      - VAULT_CLUSTER_ADDR=http://vault:8201
      - VAULT_TOKEN=${VAULT_TOKEN}
    volumes:
      - vault_data:/opt/vault/data
      - ../vault/config:/etc/vault
      - ../vault/tls:/etc/vault/tls
    depends_on:
      - keycloak
    healthcheck:
      test: [ "CMD", "vault", "status", "-address=http://localhost:8200" ]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"

  elasticsearch:
    image: elasticsearch:9.2.0
    container_name: elasticsearch_service
    environment:
      - node.name=es01
      - cluster.name=${CLUSTER_NAME}
      - discovery.type=single-node
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=false
      - xpack.license.self_generated.type=${LICENSE}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data:/usr/share/elasticsearch/data
    expose:
      - "9200"  # Elasticsearch REST API
    healthcheck:
      test: [ "CMD-SHELL", "curl -s http://localhost:9200 >/dev/null || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  default:
    name: video_streaming_network
    external: true
volumes:
  minio_data:
  grafana_data:
  prometheus_data:
  postgres_data:
  vault_data:
  es_data:
# docker compose -p video_streaming_stack -f ./Docker/docker-compose.yml build
# docker compose -p video_streaming_stack -f ./Docker/docker-compose.yml up -d

#docker compose -p video_streaming_stack -f ./Docker/docker-compose.yml up -d --build
