services:
  bff:
    build:
      context: ..
      dockerfile: ./backend/Dockerfile
    container_name: bff_service
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - ffmpeg

  frontend:
    build:
      context: ..
      dockerfile: ./frontend/Dockerfile
    container_name: frontend_service
    ports:
      - "8001:8001"
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 1m30s
      timeout: 5s
      retries: 5
      start_period: 40s
    restart: unless-stopped

  ffmpeg:
    image: jrottenberg/ffmpeg:latest
    container_name: ffmpeg_service
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all

  minio:
    image: minio/minio
    container_name: minio_service
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}

  nginx:
    build:
      context: ..
      dockerfile: ./gateway/Dockerfile
    container_name: nginx_gateway
    ports:
      - "80:80"
    depends_on:
      - bff
      - frontend

#  prometheus:
#    image: prom/prometheus:latest
#    volumes:
#      - ./prometheus.yml:/etc/prometheus/prometheus.yml
#    ports:
#      - "9090:9090"
#
#  grafana:
#    image: grafana/grafana:latest
#    ports:
#      - "3000:3000"
#    depends_on:
#      - prometheus


networks:
  default:
    name: video_streaming_network