apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
  namespace: video-streaming
data:
  vault.hcl: |
    listener "tcp" {
      address                 = "0.0.0.0:8200"
      # tls_cert_file = "/etc/vault/tls/vault.crt"
      # tls_key_file  = "/etc/vault/tls/vault.key"
      tls_disable             = 1
      proxy_protocol_behavior = "use_always"
    }


    storage "raft" {
      path    = "/opt/vault/data"
      node_id = "vault-1"
    }

    ui            = true
    # max_lease_ttl     = "2160h"
    # default_lease_ttl = "2160h"
    log_level     = "INFO"
    api_addr      = "http://vault:8200"
    cluster_addr  = "http://vault:8201"
    disable_mlock = true

    audit "file" {
      path = "/var/log/vault_audit.log"
    }
