apiVersion: apps/v1
kind: Deployment
metadata:
  name: promtail
  namespace: video-streaming
spec:
  replicas: 1
  selector:
    matchLabels:
      app: promtail
  template:
    metadata:
      labels:
        app: promtail
    spec:
      serviceAccountName: vault-auth
      containers:
        - name: promtail
          image: grafana/promtail:latest
          imagePullPolicy: IfNotPresent
          args: ["-config.file=/etc/promtail/promtail-config.yaml"]
          securityContext:
            privileged: true
          ports:
            - containerPort: 9080
              name: http
          volumeMounts:
            - name: promtail-config
              mountPath: /etc/promtail/promtail-config.yaml
              subPath: promtail-config.yaml
            - name: docker-containers
              mountPath: /var/lib/docker/containers
              readOnly: true
            - name: docker-socket
              mountPath: /var/run/docker.sock
      volumes:
        - name: promtail-config
          configMap:
            name: promtail-config
        - name: docker-containers
          hostPath:
            path: /var/lib/docker/containers
            type: Directory
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
            type: Socket
---
apiVersion: v1
kind: Service
metadata:
  name: promtail
  namespace: video-streaming
spec:
  selector:
    app: promtail
  ports:
    - name: http
      port: 9080
      targetPort: http
