"""added few schema columns

Revision ID: 03210df0748a
Revises: fb36c1a31afe
Create Date: 2025-10-27 18:56:38.131332

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "03210df0748a"
down_revision: Union[str, Sequence[str], None] = "fb36c1a31afe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("reaction_types", sa.Column("path", sa.String(), nullable=True))
    op.drop_index(op.f("ix_videos_user_id"), table_name="videos")
    op.create_index("ix_videos_user_id", "videos", ["channel_id"], unique=False)
    op.drop_constraint(op.f("videos_user_id_fkey"), "videos", type_="foreignkey")
    op.drop_column("videos", "user_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "videos", sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False)
    )
    op.create_foreign_key(
        op.f("videos_user_id_fkey"), "videos", "users", ["user_id"], ["id"]
    )
    op.drop_index("ix_videos_user_id", table_name="videos")
    op.create_index(op.f("ix_videos_user_id"), "videos", ["user_id"], unique=False)
    op.drop_column("reaction_types", "path")
    # ### end Alembic commands ###
