"""minor fixes

Revision ID: fb36c1a31afe
Revises: d40d3fb3b08b
Create Date: 2025-10-27 18:11:19.057474

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fb36c1a31afe"
down_revision: Union[str, Sequence[str], None] = "d40d3fb3b08b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("channels", sa.Column("description", sa.Text(), nullable=True))
    op.add_column(
        "channels",
        sa.Column("views_count", sa.Integer(), server_default="0", nullable=False),
    )
    op.add_column("channels", sa.Column("avatar_path", sa.String(), nullable=True))
    op.add_column("channels", sa.Column("background_path", sa.String(), nullable=True))
    op.add_column(
        "channels",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column("comments", sa.Column("parent_id", sa.UUID(), nullable=True))
    op.create_foreign_key(None, "comments", "comments", ["parent_id"], ["id"])
    op.add_column("notifications", sa.Column("link", sa.Text(), nullable=False))
    op.drop_column("notifications", "lnk")
    op.create_unique_constraint(None, "subscriptions", ["subscriber_id", "channel_id"])
    op.drop_column("videos", "background_path")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "videos",
        sa.Column("background_path", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "subscriptions", type_="unique")
    op.add_column(
        "notifications",
        sa.Column("lnk", sa.TEXT(), autoincrement=False, nullable=False),
    )
    op.drop_column("notifications", "link")
    op.drop_constraint(None, "comments", type_="foreignkey")
    op.drop_column("comments", "parent_id")
    op.drop_column("channels", "created_at")
    op.drop_column("channels", "background_path")
    op.drop_column("channels", "avatar_path")
    op.drop_column("channels", "views_count")
    op.drop_column("channels", "description")
    # ### end Alembic commands ###
