"""integrated fastapi-users models

Revision ID: 5d79f349d185
Revises: 6627ad3aa405
Create Date: 2026-03-15 10:50:48.773392

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5d79f349d185"
down_revision: Union[str, Sequence[str], None] = "6627ad3aa405"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # rename password column
    op.alter_column(
        "users",
        "hash_password",
        new_column_name="hashed_password",
        existing_type=sa.String(),
        nullable=False,
    )

    # add boolean columns with defaults
    op.add_column(
        "users",
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()),
    )
    op.add_column(
        "users",
        sa.Column(
            "is_superuser", sa.Boolean(), nullable=False, server_default=sa.false()
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "is_verified", sa.Boolean(), nullable=False, server_default=sa.false()
        ),
    )

    # create unique constraint
    op.create_unique_constraint(None, "subscriptions", ["subscriber_id", "channel_id"])

    # remove server defaults if you want
    with op.batch_alter_table("users") as batch_op:
        batch_op.alter_column("is_active", server_default=None)
        batch_op.alter_column("is_superuser", server_default=None)
        batch_op.alter_column("is_verified", server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("hash_password", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_column("users", "is_verified")
    op.drop_column("users", "is_superuser")
    op.drop_column("users", "is_active")
    op.drop_column("users", "hashed_password")
    op.drop_constraint(None, "subscriptions", type_="unique")
    # ### end Alembic commands ###
