apiVersion: v1
kind: Service
metadata:
  name: {{ include "video-streaming.fullname" . }}-convertor
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ include "video-streaming.name" . }}
    component: convertor
  ports:
    - port: 9102
      targetPort: 9102
      protocol: TCP
