stages:
  - detect
  - build
  - deploy

variables:
  REGISTRY: $CI_REGISTRY/$CI_PROJECT_PATH

# ---------------- Detect changed services ----------------
detect-changes:
  stage: detect
  image: alpine:latest
  script:
    - apk add --no-cache git
    - echo "Checking changed folders..."
    - |
      for SERVICE in backend services/convertor services/moderation frontend; do
        if git diff --name-only $CI_COMMIT_BEFORE_SHA $CI_COMMIT_SHA | grep -q "^$SERVICE/"; then
          echo "$SERVICE changed"
          echo "$SERVICE=true" >> changes.env
        else
          echo "$SERVICE=false" >> changes.env
        fi
      done
  artifacts:
    reports:
      dotenv: changes.env

# ---------------- Build & push Docker images ----------------
deploy:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  needs:
    - detect-changes
  parallel:
    matrix:
      - SERVICE: backend
      - SERVICE: convertor
      - SERVICE: moderation
      - SERVICE: frontend
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - |
      if [ "$SERVICE" = "frontend" ]; then
        PATH_TO_SERVICE="./frontend"
      elif [ "$SERVICE" = "convertor" ]; then
        PATH_TO_SERVICE="./services/convertor"
      elif [ "$SERVICE" = "moderation" ]; then
        PATH_TO_SERVICE="./services/moderation"
      else
        PATH_TO_SERVICE="./backend"
      fi
    - |
      if grep -q "^$SERVICE=true" changes.env; then
        IMAGE="$REGISTRY/$SERVICE:$CI_COMMIT_SHA"
        docker build -t $IMAGE $PATH_TO_SERVICE
        docker push $IMAGE
        docker tag $IMAGE $REGISTRY/$SERVICE:latest
        docker push $REGISTRY/$SERVICE:latest
        echo "✅ Pushed $IMAGE"
      else
        echo "$SERVICE unchanged, skipping build"
      fi
  environment:
    name: stage
