name: "Auto PR to Stage"

on:
  workflow_run:
    workflows: [ "CI for dev branch" ]
    types: [ completed ]
  workflow_dispatch:
  push:
    branches:
      - dev

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pr:
    runs-on: ubuntu-latest
    if: >
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'workflow_run' &&
       github.event.workflow_run.conclusion == 'success' &&
       github.event.workflow_run.head_branch == 'dev')
    steps:
      - name: Checkout dev (full fetch)
        uses: actions/checkout@v4
        with:
          ref: dev
          fetch-depth: 0

  pull-request:
    needs: create-pr
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: pull-request
        uses: diillson/auto-pull-request@v1.0.1
        with:
          source_branch: "dev"
          destination_branch: "stage"
          pr_title: "Pulling ${{ github.ref }} into master"
          pr_body: |
            :crown: *An automated PR*
