name: "Auto PR to Stage"

on:
  workflow_run:
    workflows: [ "CI for dev branch" ]
    types: [ completed ]

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pr:
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'dev'

    steps:
      - name: Checkout dev (full fetch)
        uses: actions/checkout@v4
        with:
          ref: dev
          fetch-depth: 0

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Auto PR from dev → stage"
          branch: dev
          base: stage
          title: "Merge dev into stage (auto PR)"
          body: "This PR was automatically created after successful CI."
          labels: "auto-pr"
