name: "Auto PR to Stage"

on:
  workflow_run:
    workflows: [ "CI for dev branch" ]
    types:
      - completed

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-pr:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Checkout dev branch
        uses: actions/checkout@v4
        with:
          ref: dev
          fetch-depth: 0

      - name: Create Pull Request
        uses: diillson/auto-pull-request@v1.0.1
        with:
          source_branch: dev
          destination_branch: stage
          pr_title: "Merge dev into stage (auto PR)"
          pr_body: "Auto PR after successful CI"
          pr_label: auto-pr
          github_token: ${{ secrets.GITHUB_TOKEN }}
